/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is
 * provided to support globbing requires, custom xtypes, and other
 * metadata-driven class system features
 */
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is
 * provided to support globbing requires, custom xtypes, and other
 * metadata-driven class system features
 */
Ext.Loader.addClassPathMappings({
  "": "app",
  "Ext": "touch/src",
  "Ext-more": "touch/src/core/Ext-more.js",
  "Ext.DomHelper": "touch/src/dom/Helper.js",
  "Ext.DomQuery": "touch/src/dom/Query.js",
  "Ext.Element-alignment": "touch/src/dom/Element.alignment.js",
  "Ext.Element-all": "touch/src/dom/Element.traversal.js",
  "Ext.Element-insertion": "touch/src/dom/Element.insertion.js",
  "Ext.Element-position": "touch/src/dom/Element.position.js",
  "Ext.Element-static": "touch/src/dom/Element.static.js",
  "Ext.Element-style": "touch/src/dom/Element.style.js",
  "Ext.Element-traversal": "touch/src/dom/Element.traversal.js",
  "Ext.core.DomQuery": "touch/src/dom/Query.js",
  "Ext.device.Purchases.Product": "touch/src/device/purchases/Sencha.js",
  "Ext.device.filesystem.DirectoryEntry": "touch/src/device/filesystem/Sencha.js",
  "Ext.device.filesystem.Entry": "touch/src/device/filesystem/Sencha.js",
  "Ext.device.filesystem.FileEntry": "touch/src/device/filesystem/Sencha.js",
  "Ext.device.filesystem.FileSystem": "touch/src/device/filesystem/Sencha.js",
  "Ext.device.purchases.Purchase": "touch/src/device/purchases/Sencha.js",
  "Ext.device.sqlite.Database": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSet": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSetRowList": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLTransaction": "touch/src/device/sqlite/Sencha.js",
  "Ext.ux": "ux",
  "Ext.ux.ActionOverFlowMenuButton": "touch/src/ux/ActionOverFlowMenuButton.js",
  "Ext.ux.ApplicationMenu": "touch/src/ux/ApplicationMenu.js",
  "Ext.ux.ContextMenu": "touch/src/ux/ContextMenu.js",
  "Ext.ux.MenuButton": "touch/src/ux/MenuButton.js",
  "Ext.ux.TabMenuButton": "touch/src/ux/TabMenuButton.js",
  "Ext.ux.device": "touch/src/ux/device",
  "Ext.ux.parse": "touch/src/ux/parse",
  "Mat": "app",
  "Mat.controller.BlocoJo": "app/controller/BlocoJogo.js",
  "Mat.view.MenuJogo": "app/view/SelectNiveis.js"
});

Ext.ClassManager.addNameAlternateMappings({
  ".controller.Audios": [],
  ".controller.Fotos": [],
  ".controller.Videos": [],
  ".model.Audios": [],
  ".model.Fotos": [],
  ".model.Videos": [],
  ".store.Audios": [],
  ".store.Fotos": [],
  ".store.Videos": [],
  ".view.Audios.Audios": [],
  ".view.Audios.ContainerAudios": [],
  ".view.Audios.EditorAudios": [],
  ".view.Audios.ListAudios": [],
  ".view.Audios.SearchBarAudios": [],
  ".view.Fotos.ContainerFotos": [],
  ".view.Fotos.EditorFotos": [],
  ".view.Fotos.Fotos": [],
  ".view.Fotos.ListFotos": [],
  ".view.Fotos.SearchBarFotos": [],
  ".view.Videos.ContainerVideos": [],
  ".view.Videos.EditorVideos": [],
  ".view.Videos.ListVideos": [],
  ".view.Videos.SearchBarVideos": [],
  ".view.Videos.Videos": [],
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.AbstractPlugin": [],
  "Ext.ActionSheet": [],
  "Ext.Ajax": [],
  "Ext.Anim": [],
  "Ext.AnimationQueue": [],
  "Ext.Audio": [],
  "Ext.BingMap": [],
  "Ext.Button": [],
  "Ext.Component": [
    "Ext.lib.Component"
  ],
  "Ext.ComponentManager": [
    "Ext.ComponentMgr"
  ],
  "Ext.ComponentQuery": [],
  "Ext.Container": [
    "Ext.lib.Container"
  ],
  "Ext.Decorator": [],
  "Ext.Evented": [
    "Ext.EventedBase"
  ],
  "Ext.Img": [],
  "Ext.ItemCollection": [],
  "Ext.Label": [],
  "Ext.LoadMask": [],
  "Ext.Map": [],
  "Ext.Mask": [],
  "Ext.Media": [],
  "Ext.Menu": [],
  "Ext.MessageBox": [],
  "Ext.Panel": [
    "Ext.lib.Panel"
  ],
  "Ext.ProgressIndicator": [],
  "Ext.Promise": [],
  "Ext.SegmentedButton": [],
  "Ext.Sheet": [],
  "Ext.Sortable": [],
  "Ext.Spacer": [],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Title": [],
  "Ext.TitleBar": [],
  "Ext.Toolbar": [],
  "Ext.Video": [],
  "Ext.XTemplate": [],
  "Ext.XTemplateCompiler": [],
  "Ext.XTemplateParser": [],
  "Ext.app.Action": [],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.History": [],
  "Ext.app.Profile": [],
  "Ext.app.Route": [],
  "Ext.app.Router": [],
  "Ext.behavior.Behavior": [],
  "Ext.behavior.Draggable": [],
  "Ext.behavior.Scrollable": [],
  "Ext.behavior.Translatable": [],
  "Ext.carousel.Carousel": [
    "Ext.Carousel"
  ],
  "Ext.carousel.Indicator": [
    "Ext.Carousel.Indicator"
  ],
  "Ext.carousel.Infinite": [],
  "Ext.carousel.Item": [],
  "Ext.data.ArrayStore": [],
  "Ext.data.Batch": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [],
  "Ext.data.Error": [],
  "Ext.data.Errors": [],
  "Ext.data.Field": [],
  "Ext.data.JsonP": [
    "Ext.util.JSONP"
  ],
  "Ext.data.JsonStore": [],
  "Ext.data.Model": [
    "Ext.data.Record"
  ],
  "Ext.data.ModelManager": [
    "Ext.ModelMgr",
    "Ext.ModelManager"
  ],
  "Ext.data.NodeInterface": [
    "Ext.data.Node"
  ],
  "Ext.data.NodeStore": [],
  "Ext.data.Operation": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [],
  "Ext.data.StoreManager": [
    "Ext.StoreMgr",
    "Ext.data.StoreMgr",
    "Ext.StoreManager"
  ],
  "Ext.data.TreeStore": [],
  "Ext.data.Types": [],
  "Ext.data.Validations": [
    "Ext.data.validations"
  ],
  "Ext.data.association.Association": [
    "Ext.data.Association"
  ],
  "Ext.data.association.BelongsTo": [
    "Ext.data.BelongsToAssociation"
  ],
  "Ext.data.association.HasMany": [
    "Ext.data.HasManyAssociation"
  ],
  "Ext.data.association.HasOne": [
    "Ext.data.HasOneAssociation"
  ],
  "Ext.data.identifier.Sequential": [],
  "Ext.data.identifier.Simple": [],
  "Ext.data.identifier.Uuid": [],
  "Ext.data.plugin.Buffered": [],
  "Ext.data.proxy.Ajax": [
    "Ext.data.HttpProxy",
    "Ext.data.AjaxProxy"
  ],
  "Ext.data.proxy.Client": [
    "Ext.proxy.ClientProxy"
  ],
  "Ext.data.proxy.Direct": [
    "Ext.data.DirectProxy"
  ],
  "Ext.data.proxy.JsonP": [
    "Ext.data.ScriptTagProxy"
  ],
  "Ext.data.proxy.LocalStorage": [
    "Ext.data.LocalStorageProxy"
  ],
  "Ext.data.proxy.Memory": [
    "Ext.data.MemoryProxy"
  ],
  "Ext.data.proxy.Proxy": [
    "Ext.data.DataProxy",
    "Ext.data.Proxy"
  ],
  "Ext.data.proxy.Rest": [
    "Ext.data.RestProxy"
  ],
  "Ext.data.proxy.Server": [
    "Ext.data.ServerProxy"
  ],
  "Ext.data.proxy.SessionStorage": [
    "Ext.data.SessionStorageProxy"
  ],
  "Ext.data.proxy.Sql": [
    "Ext.data.proxy.SQL"
  ],
  "Ext.data.proxy.WebStorage": [
    "Ext.data.WebStorageProxy"
  ],
  "Ext.data.reader.Array": [
    "Ext.data.ArrayReader"
  ],
  "Ext.data.reader.Json": [
    "Ext.data.JsonReader"
  ],
  "Ext.data.reader.Reader": [
    "Ext.data.Reader",
    "Ext.data.DataReader"
  ],
  "Ext.data.reader.Xml": [
    "Ext.data.XmlReader"
  ],
  "Ext.data.writer.Json": [
    "Ext.data.JsonWriter"
  ],
  "Ext.data.writer.Writer": [
    "Ext.data.DataWriter",
    "Ext.data.Writer"
  ],
  "Ext.data.writer.Xml": [
    "Ext.data.XmlWriter"
  ],
  "Ext.dataview.DataView": [
    "Ext.DataView"
  ],
  "Ext.dataview.IndexBar": [
    "Ext.IndexBar"
  ],
  "Ext.dataview.List": [
    "Ext.List"
  ],
  "Ext.dataview.ListItemHeader": [],
  "Ext.dataview.NestedList": [
    "Ext.NestedList"
  ],
  "Ext.dataview.component.Container": [],
  "Ext.dataview.component.DataItem": [],
  "Ext.dataview.component.ListItem": [],
  "Ext.dataview.component.SimpleListItem": [],
  "Ext.dataview.element.Container": [],
  "Ext.dataview.element.List": [],
  "Ext.device.Accelerometer": [],
  "Ext.device.Browser": [],
  "Ext.device.Camera": [],
  "Ext.device.Capture": [],
  "Ext.device.Communicator": [],
  "Ext.device.Compass": [],
  "Ext.device.Connection": [],
  "Ext.device.Contacts": [],
  "Ext.device.Device": [],
  "Ext.device.FileSystem": [],
  "Ext.device.Geolocation": [],
  "Ext.device.Globalization": [],
  "Ext.device.Media": [],
  "Ext.device.Notification": [],
  "Ext.device.Orientation": [],
  "Ext.device.Purchases": [],
  "Ext.device.Purchases.Product": [],
  "Ext.device.Push": [],
  "Ext.device.SQLite": [],
  "Ext.device.Splashscreen": [],
  "Ext.device.Storage": [],
  "Ext.device.Tunnel": [],
  "Ext.device.accelerometer.Abstract": [],
  "Ext.device.accelerometer.Cordova": [
    "Ext.device.accelerometer.PhoneGap"
  ],
  "Ext.device.accelerometer.Simulator": [],
  "Ext.device.browser.Abstract": [],
  "Ext.device.browser.Cordova": [],
  "Ext.device.browser.Simulator": [],
  "Ext.device.browser.Window": [],
  "Ext.device.camera.Abstract": [],
  "Ext.device.camera.Cordova": [
    "Ext.device.camera.PhoneGap"
  ],
  "Ext.device.camera.Sencha": [],
  "Ext.device.camera.Simulator": [],
  "Ext.device.capture.Abstract": [
    "Ext.device.capture.Simulator"
  ],
  "Ext.device.capture.Cordova": [],
  "Ext.device.communicator.Android": [],
  "Ext.device.communicator.Default": [],
  "Ext.device.compass.Abstract": [],
  "Ext.device.compass.Cordova": [
    "Ext.device.compass.PhoneGap"
  ],
  "Ext.device.compass.Simulator": [],
  "Ext.device.connection.Abstract": [],
  "Ext.device.connection.Cordova": [
    "Ext.device.connection.PhoneGap"
  ],
  "Ext.device.connection.Sencha": [],
  "Ext.device.connection.Simulator": [],
  "Ext.device.contacts.Abstract": [],
  "Ext.device.contacts.Cordova": [
    "Ext.device.contacts.PhoneGap"
  ],
  "Ext.device.contacts.Sencha": [],
  "Ext.device.device.Abstract": [],
  "Ext.device.device.Cordova": [
    "Ext.device.device.PhoneGap"
  ],
  "Ext.device.device.Sencha": [],
  "Ext.device.device.Simulator": [],
  "Ext.device.filesystem.Abstract": [],
  "Ext.device.filesystem.Chrome": [],
  "Ext.device.filesystem.Cordova": [
    "Ext.device.filesystem.PhoneGap"
  ],
  "Ext.device.filesystem.DirectoryEntry": [],
  "Ext.device.filesystem.Entry": [],
  "Ext.device.filesystem.FileEntry": [],
  "Ext.device.filesystem.FileSystem": [],
  "Ext.device.filesystem.HTML5": [],
  "Ext.device.filesystem.Sencha": [],
  "Ext.device.filesystem.Simulator": [],
  "Ext.device.geolocation.Abstract": [],
  "Ext.device.geolocation.Cordova": [
    "Ext.device.geolocation.PhoneGap"
  ],
  "Ext.device.geolocation.Sencha": [],
  "Ext.device.geolocation.Simulator": [],
  "Ext.device.globalization.Abstract": [],
  "Ext.device.globalization.Cordova": [
    "Ext.device.globalization.PhoneGap"
  ],
  "Ext.device.globalization.Simulator": [],
  "Ext.device.media.Abstract": [],
  "Ext.device.media.Cordova": [
    "Ext.device.media.PhoneGap"
  ],
  "Ext.device.notification.Abstract": [],
  "Ext.device.notification.Cordova": [
    "Ext.device.notification.PhoneGap"
  ],
  "Ext.device.notification.Sencha": [],
  "Ext.device.notification.Simulator": [],
  "Ext.device.orientation.Abstract": [],
  "Ext.device.orientation.HTML5": [],
  "Ext.device.orientation.Sencha": [],
  "Ext.device.purchases.Purchase": [],
  "Ext.device.purchases.Sencha": [],
  "Ext.device.push.Abstract": [],
  "Ext.device.push.Cordova": [],
  "Ext.device.push.Sencha": [],
  "Ext.device.splashscreen.Abstract": [],
  "Ext.device.splashscreen.Cordova": [
    "Ext.device.splashscreen.PhoneGap"
  ],
  "Ext.device.splashscreen.Simulator": [],
  "Ext.device.sqlite.Database": [],
  "Ext.device.sqlite.SQLResultSet": [],
  "Ext.device.sqlite.SQLResultSetRowList": [],
  "Ext.device.sqlite.SQLTransaction": [],
  "Ext.device.sqlite.Sencha": [],
  "Ext.device.storage.Abstract": [],
  "Ext.device.storage.Cordova": [
    "Ext.device.storage.PhoneGap"
  ],
  "Ext.device.storage.HTML5.Database": [],
  "Ext.device.storage.HTML5.HTML5": [],
  "Ext.device.storage.HTML5.SQLStatement": [],
  "Ext.device.storage.Simulator": [],
  "Ext.device.tunnel.Abstract": [],
  "Ext.device.tunnel.Connection": [],
  "Ext.device.tunnel.Sencha": [],
  "Ext.device.tunnel.Simulator": [],
  "Ext.direct.Event": [],
  "Ext.direct.ExceptionEvent": [],
  "Ext.direct.JsonProvider": [],
  "Ext.direct.Manager": [
    "Ext.Direct"
  ],
  "Ext.direct.PollingProvider": [],
  "Ext.direct.Provider": [],
  "Ext.direct.RemotingEvent": [],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [],
  "Ext.direct.Transaction": [
    "Ext.Direct.Transaction"
  ],
  "Ext.dom.CompositeElement": [
    "Ext.CompositeElement"
  ],
  "Ext.event.Controller": [],
  "Ext.event.Dispatcher": [],
  "Ext.event.Dom": [],
  "Ext.event.Event": [
    "Ext.EventObject"
  ],
  "Ext.event.ListenerStack": [],
  "Ext.event.Touch": [],
  "Ext.event.publisher.ComponentDelegation": [],
  "Ext.event.publisher.ComponentPaint": [],
  "Ext.event.publisher.ComponentSize": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.event.publisher.TouchGesture": [],
  "Ext.event.recognizer.DoubleTap": [],
  "Ext.event.recognizer.Drag": [],
  "Ext.event.recognizer.EdgeSwipe": [],
  "Ext.event.recognizer.HorizontalSwipe": [],
  "Ext.event.recognizer.LongPress": [],
  "Ext.event.recognizer.MultiTouch": [],
  "Ext.event.recognizer.Pinch": [],
  "Ext.event.recognizer.Recognizer": [],
  "Ext.event.recognizer.Rotate": [],
  "Ext.event.recognizer.SingleTouch": [],
  "Ext.event.recognizer.Swipe": [],
  "Ext.event.recognizer.Tap": [],
  "Ext.event.recognizer.Touch": [],
  "Ext.event.recognizer.VerticalSwipe": [],
  "Ext.field.Checkbox": [
    "Ext.form.Checkbox"
  ],
  "Ext.field.DatePicker": [
    "Ext.form.DatePicker"
  ],
  "Ext.field.DatePickerNative": [
    "Ext.form.DatePickerNative"
  ],
  "Ext.field.Email": [
    "Ext.form.Email"
  ],
  "Ext.field.Field": [
    "Ext.form.Field"
  ],
  "Ext.field.File": [],
  "Ext.field.FileInput": [],
  "Ext.field.Hidden": [
    "Ext.form.Hidden"
  ],
  "Ext.field.Input": [],
  "Ext.field.Number": [
    "Ext.form.Number"
  ],
  "Ext.field.Password": [
    "Ext.form.Password"
  ],
  "Ext.field.Radio": [
    "Ext.form.Radio"
  ],
  "Ext.field.Search": [
    "Ext.form.Search"
  ],
  "Ext.field.Select": [
    "Ext.form.Select"
  ],
  "Ext.field.Slider": [
    "Ext.form.Slider"
  ],
  "Ext.field.Spinner": [
    "Ext.form.Spinner"
  ],
  "Ext.field.Text": [
    "Ext.form.Text"
  ],
  "Ext.field.TextArea": [
    "Ext.form.TextArea"
  ],
  "Ext.field.TextAreaInput": [],
  "Ext.field.Toggle": [
    "Ext.form.Toggle"
  ],
  "Ext.field.Url": [
    "Ext.form.Url"
  ],
  "Ext.form.FieldSet": [],
  "Ext.form.Panel": [
    "Ext.form.FormPanel"
  ],
  "Ext.fx.Animation": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [],
  "Ext.fx.animation.Fade": [
    "Ext.fx.animation.FadeIn"
  ],
  "Ext.fx.animation.FadeOut": [],
  "Ext.fx.animation.Flip": [],
  "Ext.fx.animation.Pop": [
    "Ext.fx.animation.PopIn"
  ],
  "Ext.fx.animation.PopOut": [],
  "Ext.fx.animation.Slide": [
    "Ext.fx.animation.SlideIn"
  ],
  "Ext.fx.animation.SlideOut": [],
  "Ext.fx.animation.Wipe": [
    "Ext.fx.animation.WipeIn"
  ],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [],
  "Ext.fx.easing.EaseOut": [],
  "Ext.fx.easing.Linear": [],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [],
  "Ext.fx.layout.card.Cube": [],
  "Ext.fx.layout.card.Fade": [],
  "Ext.fx.layout.card.Flip": [],
  "Ext.fx.layout.card.Pop": [],
  "Ext.fx.layout.card.Reveal": [],
  "Ext.fx.layout.card.Scroll": [],
  "Ext.fx.layout.card.ScrollCover": [],
  "Ext.fx.layout.card.ScrollReveal": [],
  "Ext.fx.layout.card.Slide": [],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [],
  "Ext.layout.Abstract": [],
  "Ext.layout.Box": [],
  "Ext.layout.Card": [],
  "Ext.layout.Default": [],
  "Ext.layout.Fit": [],
  "Ext.layout.FlexBox": [],
  "Ext.layout.Float": [],
  "Ext.layout.HBox": [],
  "Ext.layout.VBox": [],
  "Ext.layout.wrapper.BoxDock": [],
  "Ext.layout.wrapper.Dock": [],
  "Ext.layout.wrapper.Inner": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.Filterable": [],
  "Ext.mixin.Mixin": [],
  "Ext.mixin.Observable": [
    "Ext.util.Observable"
  ],
  "Ext.mixin.Progressable": [],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Sortable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.navigation.Bar": [],
  "Ext.navigation.View": [
    "Ext.NavigationView"
  ],
  "Ext.picker.Date": [
    "Ext.DatePicker"
  ],
  "Ext.picker.Picker": [
    "Ext.Picker"
  ],
  "Ext.picker.Slot": [
    "Ext.Picker.Slot"
  ],
  "Ext.plugin.BufferedList": [],
  "Ext.plugin.ListPaging": [],
  "Ext.plugin.PullRefresh": [],
  "Ext.plugin.SortableList": [],
  "Ext.scroll.Indicator": [
    "Ext.util.Indicator"
  ],
  "Ext.scroll.Scroller": [],
  "Ext.scroll.View": [
    "Ext.util.ScrollView"
  ],
  "Ext.scroll.indicator.Abstract": [],
  "Ext.scroll.indicator.CssTransform": [],
  "Ext.scroll.indicator.Rounded": [],
  "Ext.scroll.indicator.ScrollPosition": [],
  "Ext.slider.Slider": [],
  "Ext.slider.Thumb": [],
  "Ext.slider.Toggle": [],
  "Ext.tab.Bar": [
    "Ext.TabBar"
  ],
  "Ext.tab.Panel": [
    "Ext.TabPanel"
  ],
  "Ext.tab.Tab": [
    "Ext.Tab"
  ],
  "Ext.table.Cell": [],
  "Ext.table.Row": [],
  "Ext.table.Table": [],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Audio": [],
  "Ext.util.BufferedCollection": [],
  "Ext.util.Collection": [],
  "Ext.util.DelayedTask": [],
  "Ext.util.Draggable": [],
  "Ext.util.Droppable": [],
  "Ext.util.Filter": [],
  "Ext.util.Format": [],
  "Ext.util.Geolocation": [
    "Ext.util.GeoLocation"
  ],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.Inflector": [],
  "Ext.util.InputBlocker": [],
  "Ext.util.LineSegment": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.PositionMap": [],
  "Ext.util.Region": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TapRepeater": [],
  "Ext.util.Translatable": [],
  "Ext.util.TranslatableGroup": [],
  "Ext.util.TranslatableList": [],
  "Ext.util.Wrapper": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.Default": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.ux.ActionOverFlowMenuButton": [],
  "Ext.ux.ApplicationMenu": [],
  "Ext.ux.ContextMenu": [],
  "Ext.ux.MenuButton": [],
  "Ext.ux.TabMenuButton": [],
  "Ext.ux.device.Analytics": [],
  "Ext.ux.device.Twitter": [],
  "Ext.ux.device.analytics.Abstract": [],
  "Ext.ux.device.analytics.Cordova": [],
  "Ext.ux.device.twitter.Abstract": [],
  "Ext.ux.device.twitter.Cordova": [],
  "Ext.ux.parse.Helper": [
    "ParseHelper"
  ],
  "Ext.ux.parse.Model": [],
  "Ext.ux.parse.Proxy": [],
  "Ext.ux.parse.Reader": [],
  "Ext.ux.parse.Store": [],
  "Ext.ux.parse.association.Pointer": [],
  "Ext.ux.parse.association.Relation": [],
  "Ext.ux.slidenavigation.View": [],
  "Ext.viewport.Android": [],
  "Ext.viewport.Default": [],
  "Ext.viewport.Ios": [],
  "Ext.viewport.Viewport": [],
  "Ext.viewport.WindowsPhone": [
    "Ext.viewport.WP"
  ],
  "Mat.controller.BlocoJo": [],
  "Mat.controller.Classes": [],
  "Mat.controller.EngineJogo": [],
  "Mat.controller.Fases": [],
  "Mat.controller.Jogo": [],
  "Mat.controller.MainJogo": [],
  "Mat.controller.Niveis": [],
  "Mat.controller.Ranking": [],
  "Mat.controller.Usuarios": [],
  "Mat.model.Classes": [],
  "Mat.model.Fases": [],
  "Mat.model.FasesLocal": [],
  "Mat.model.Jogo": [],
  "Mat.model.JogoLocal": [],
  "Mat.model.Niveis": [],
  "Mat.model.NiveisLocal": [],
  "Mat.model.Ranking": [],
  "Mat.model.Usuarios": [],
  "Mat.store.Classes": [],
  "Mat.store.Fases": [],
  "Mat.store.FasesLocal": [],
  "Mat.store.Jogo": [],
  "Mat.store.JogoLocal": [],
  "Mat.store.Niveis": [],
  "Mat.store.NiveisLocal": [],
  "Mat.store.Ranking": [],
  "Mat.store.Usuarios": [],
  "Mat.view.BlocoJogo": [],
  "Mat.view.Classes.Classes": [],
  "Mat.view.Classes.ContainerClasses": [],
  "Mat.view.Classes.EditorClasses": [],
  "Mat.view.Classes.ListClasses": [],
  "Mat.view.Classes.SearchBarClasses": [],
  "Mat.view.EngineJogo": [],
  "Mat.view.Fases.ContainerFases": [],
  "Mat.view.Fases.EditorFases": [],
  "Mat.view.Fases.Fases": [],
  "Mat.view.Fases.ListFases": [],
  "Mat.view.Fases.SearchBarFases": [],
  "Mat.view.Jogo.ContainerJogo": [],
  "Mat.view.Jogo.EditorJogo": [],
  "Mat.view.Jogo.Jogo": [],
  "Mat.view.Jogo.ListJogo": [],
  "Mat.view.Jogo.SearchBarJogo": [],
  "Mat.view.Main": [],
  "Mat.view.MainJogo": [],
  "Mat.view.MenuJogo": [],
  "Mat.view.Niveis.ContainerNiveis": [],
  "Mat.view.Niveis.EditorNiveis": [],
  "Mat.view.Niveis.ListNiveis": [],
  "Mat.view.Niveis.Niveis": [],
  "Mat.view.Niveis.SearchBarNiveis": [],
  "Mat.view.Ranking.ContainerRanking": [],
  "Mat.view.Ranking.EditorRanking": [],
  "Mat.view.Ranking.ListRanking": [],
  "Mat.view.Ranking.Ranking": [],
  "Mat.view.Ranking.SearchBarRanking": [],
  "Mat.view.SelecionaFases": [],
  "Mat.view.SelecionaNiveis": [],
  "Mat.view.Usuarios.ContainerUsuarios": [],
  "Mat.view.Usuarios.EditorUsuarios": [],
  "Mat.view.Usuarios.ListUsuarios": [],
  "Mat.view.Usuarios.SearchBarUsuarios": [],
  "Mat.view.Usuarios.Usuarios": []
});

Ext.ClassManager.addNameAliasMappings({
  ".controller.Audios": [],
  ".controller.Fotos": [],
  ".controller.Videos": [],
  ".model.Audios": [],
  ".model.Fotos": [],
  ".model.Videos": [],
  ".store.Audios": [],
  ".store.Fotos": [],
  ".store.Videos": [],
  ".view.Audios.Audios": [
    "widget.Audios"
  ],
  ".view.Audios.ContainerAudios": [
    "widget.ContainerAudios"
  ],
  ".view.Audios.EditorAudios": [
    "widget.EditorAudios"
  ],
  ".view.Audios.ListAudios": [
    "widget.ListAudios"
  ],
  ".view.Audios.SearchBarAudios": [
    "widget.SearchBarAudios"
  ],
  ".view.Fotos.ContainerFotos": [
    "widget.ContainerFotos"
  ],
  ".view.Fotos.EditorFotos": [
    "widget.EditorFotos"
  ],
  ".view.Fotos.Fotos": [
    "widget.Fotos"
  ],
  ".view.Fotos.ListFotos": [
    "widget.ListFotos"
  ],
  ".view.Fotos.SearchBarFotos": [
    "widget.SearchBarFotos"
  ],
  ".view.Videos.ContainerVideos": [
    "widget.ContainerVideos"
  ],
  ".view.Videos.EditorVideos": [
    "widget.EditorVideos"
  ],
  ".view.Videos.ListVideos": [
    "widget.ListVideos"
  ],
  ".view.Videos.SearchBarVideos": [
    "widget.SearchBarVideos"
  ],
  ".view.Videos.Videos": [
    "widget.Videos"
  ],
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.AbstractPlugin": [],
  "Ext.ActionSheet": [
    "widget.actionsheet"
  ],
  "Ext.Ajax": [],
  "Ext.Anim": [],
  "Ext.AnimationQueue": [],
  "Ext.Audio": [
    "widget.audio"
  ],
  "Ext.BingMap": [
    "widget.bingmap"
  ],
  "Ext.Button": [
    "widget.button"
  ],
  "Ext.Component": [
    "widget.component"
  ],
  "Ext.ComponentManager": [],
  "Ext.ComponentQuery": [],
  "Ext.Container": [
    "widget.container"
  ],
  "Ext.Decorator": [],
  "Ext.Evented": [],
  "Ext.Img": [
    "widget.image",
    "widget.img"
  ],
  "Ext.ItemCollection": [],
  "Ext.Label": [
    "widget.label"
  ],
  "Ext.LoadMask": [
    "widget.loadmask"
  ],
  "Ext.Map": [
    "widget.map"
  ],
  "Ext.Mask": [
    "widget.mask"
  ],
  "Ext.Media": [
    "widget.media"
  ],
  "Ext.Menu": [
    "widget.menu"
  ],
  "Ext.MessageBox": [],
  "Ext.Panel": [
    "widget.panel"
  ],
  "Ext.ProgressIndicator": [
    "widget.progressindicator"
  ],
  "Ext.Promise": [],
  "Ext.SegmentedButton": [
    "widget.segmentedbutton"
  ],
  "Ext.Sheet": [
    "widget.sheet"
  ],
  "Ext.Sortable": [],
  "Ext.Spacer": [
    "widget.spacer"
  ],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Title": [
    "widget.title"
  ],
  "Ext.TitleBar": [
    "widget.titlebar"
  ],
  "Ext.Toolbar": [
    "widget.toolbar"
  ],
  "Ext.Video": [
    "widget.video"
  ],
  "Ext.XTemplate": [],
  "Ext.XTemplateCompiler": [],
  "Ext.XTemplateParser": [],
  "Ext.app.Action": [],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.History": [],
  "Ext.app.Profile": [],
  "Ext.app.Route": [],
  "Ext.app.Router": [],
  "Ext.behavior.Behavior": [],
  "Ext.behavior.Draggable": [],
  "Ext.behavior.Scrollable": [],
  "Ext.behavior.Translatable": [],
  "Ext.carousel.Carousel": [
    "widget.carousel"
  ],
  "Ext.carousel.Indicator": [
    "widget.carouselindicator"
  ],
  "Ext.carousel.Infinite": [],
  "Ext.carousel.Item": [],
  "Ext.data.ArrayStore": [
    "store.array"
  ],
  "Ext.data.Batch": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [
    "store.direct"
  ],
  "Ext.data.Error": [],
  "Ext.data.Errors": [],
  "Ext.data.Field": [
    "data.field"
  ],
  "Ext.data.JsonP": [],
  "Ext.data.JsonStore": [
    "store.json"
  ],
  "Ext.data.Model": [],
  "Ext.data.ModelManager": [],
  "Ext.data.NodeInterface": [],
  "Ext.data.NodeStore": [
    "store.node"
  ],
  "Ext.data.Operation": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [
    "store.store"
  ],
  "Ext.data.StoreManager": [],
  "Ext.data.TreeStore": [
    "store.tree"
  ],
  "Ext.data.Types": [],
  "Ext.data.Validations": [],
  "Ext.data.association.Association": [],
  "Ext.data.association.BelongsTo": [
    "association.belongsto"
  ],
  "Ext.data.association.HasMany": [
    "association.hasmany"
  ],
  "Ext.data.association.HasOne": [
    "association.hasone"
  ],
  "Ext.data.identifier.Sequential": [
    "data.identifier.sequential"
  ],
  "Ext.data.identifier.Simple": [
    "data.identifier.simple"
  ],
  "Ext.data.identifier.Uuid": [
    "data.identifier.uuid"
  ],
  "Ext.data.plugin.Buffered": [
    "plugin.storebuffered"
  ],
  "Ext.data.proxy.Ajax": [
    "proxy.ajax"
  ],
  "Ext.data.proxy.Client": [],
  "Ext.data.proxy.Direct": [
    "proxy.direct"
  ],
  "Ext.data.proxy.JsonP": [
    "proxy.jsonp",
    "proxy.scripttag"
  ],
  "Ext.data.proxy.LocalStorage": [
    "proxy.localstorage"
  ],
  "Ext.data.proxy.Memory": [
    "proxy.memory"
  ],
  "Ext.data.proxy.Proxy": [
    "proxy.proxy"
  ],
  "Ext.data.proxy.Rest": [
    "proxy.rest"
  ],
  "Ext.data.proxy.Server": [
    "proxy.server"
  ],
  "Ext.data.proxy.SessionStorage": [
    "proxy.sessionstorage"
  ],
  "Ext.data.proxy.Sql": [
    "proxy.sql"
  ],
  "Ext.data.proxy.WebStorage": [],
  "Ext.data.reader.Array": [
    "reader.array"
  ],
  "Ext.data.reader.Json": [
    "reader.json"
  ],
  "Ext.data.reader.Reader": [],
  "Ext.data.reader.Xml": [
    "reader.xml"
  ],
  "Ext.data.writer.Json": [
    "writer.json"
  ],
  "Ext.data.writer.Writer": [
    "writer.base"
  ],
  "Ext.data.writer.Xml": [
    "writer.xml"
  ],
  "Ext.dataview.DataView": [
    "widget.dataview"
  ],
  "Ext.dataview.IndexBar": [],
  "Ext.dataview.List": [
    "widget.list"
  ],
  "Ext.dataview.ListItemHeader": [
    "widget.listitemheader"
  ],
  "Ext.dataview.NestedList": [
    "widget.nestedlist"
  ],
  "Ext.dataview.component.Container": [],
  "Ext.dataview.component.DataItem": [
    "widget.dataitem"
  ],
  "Ext.dataview.component.ListItem": [
    "widget.listitem"
  ],
  "Ext.dataview.component.SimpleListItem": [
    "widget.simplelistitem"
  ],
  "Ext.dataview.element.Container": [],
  "Ext.dataview.element.List": [],
  "Ext.device.Accelerometer": [],
  "Ext.device.Browser": [],
  "Ext.device.Camera": [],
  "Ext.device.Capture": [],
  "Ext.device.Communicator": [],
  "Ext.device.Compass": [],
  "Ext.device.Connection": [],
  "Ext.device.Contacts": [],
  "Ext.device.Device": [],
  "Ext.device.FileSystem": [],
  "Ext.device.Geolocation": [],
  "Ext.device.Globalization": [],
  "Ext.device.Media": [],
  "Ext.device.Notification": [],
  "Ext.device.Orientation": [],
  "Ext.device.Purchases": [],
  "Ext.device.Purchases.Product": [],
  "Ext.device.Push": [],
  "Ext.device.SQLite": [],
  "Ext.device.Splashscreen": [],
  "Ext.device.Storage": [],
  "Ext.device.Tunnel": [],
  "Ext.device.accelerometer.Abstract": [],
  "Ext.device.accelerometer.Cordova": [],
  "Ext.device.accelerometer.Simulator": [],
  "Ext.device.browser.Abstract": [],
  "Ext.device.browser.Cordova": [],
  "Ext.device.browser.Simulator": [],
  "Ext.device.browser.Window": [],
  "Ext.device.camera.Abstract": [],
  "Ext.device.camera.Cordova": [],
  "Ext.device.camera.Sencha": [],
  "Ext.device.camera.Simulator": [],
  "Ext.device.capture.Abstract": [],
  "Ext.device.capture.Cordova": [],
  "Ext.device.communicator.Android": [],
  "Ext.device.communicator.Default": [],
  "Ext.device.compass.Abstract": [],
  "Ext.device.compass.Cordova": [],
  "Ext.device.compass.Simulator": [],
  "Ext.device.connection.Abstract": [],
  "Ext.device.connection.Cordova": [],
  "Ext.device.connection.Sencha": [],
  "Ext.device.connection.Simulator": [],
  "Ext.device.contacts.Abstract": [],
  "Ext.device.contacts.Cordova": [],
  "Ext.device.contacts.Sencha": [],
  "Ext.device.device.Abstract": [],
  "Ext.device.device.Cordova": [],
  "Ext.device.device.Sencha": [],
  "Ext.device.device.Simulator": [],
  "Ext.device.filesystem.Abstract": [],
  "Ext.device.filesystem.Chrome": [],
  "Ext.device.filesystem.Cordova": [],
  "Ext.device.filesystem.DirectoryEntry": [],
  "Ext.device.filesystem.Entry": [],
  "Ext.device.filesystem.FileEntry": [],
  "Ext.device.filesystem.FileSystem": [],
  "Ext.device.filesystem.HTML5": [],
  "Ext.device.filesystem.Sencha": [],
  "Ext.device.filesystem.Simulator": [],
  "Ext.device.geolocation.Abstract": [],
  "Ext.device.geolocation.Cordova": [],
  "Ext.device.geolocation.Sencha": [],
  "Ext.device.geolocation.Simulator": [],
  "Ext.device.globalization.Abstract": [],
  "Ext.device.globalization.Cordova": [],
  "Ext.device.globalization.Simulator": [],
  "Ext.device.media.Abstract": [],
  "Ext.device.media.Cordova": [],
  "Ext.device.notification.Abstract": [],
  "Ext.device.notification.Cordova": [],
  "Ext.device.notification.Sencha": [],
  "Ext.device.notification.Simulator": [],
  "Ext.device.orientation.Abstract": [],
  "Ext.device.orientation.HTML5": [],
  "Ext.device.orientation.Sencha": [],
  "Ext.device.purchases.Purchase": [],
  "Ext.device.purchases.Sencha": [],
  "Ext.device.push.Abstract": [],
  "Ext.device.push.Cordova": [],
  "Ext.device.push.Sencha": [],
  "Ext.device.splashscreen.Abstract": [],
  "Ext.device.splashscreen.Cordova": [],
  "Ext.device.splashscreen.Simulator": [],
  "Ext.device.sqlite.Database": [],
  "Ext.device.sqlite.SQLResultSet": [],
  "Ext.device.sqlite.SQLResultSetRowList": [],
  "Ext.device.sqlite.SQLTransaction": [],
  "Ext.device.sqlite.Sencha": [],
  "Ext.device.storage.Abstract": [],
  "Ext.device.storage.Cordova": [],
  "Ext.device.storage.HTML5.Database": [],
  "Ext.device.storage.HTML5.HTML5": [],
  "Ext.device.storage.HTML5.SQLStatement": [],
  "Ext.device.storage.Simulator": [],
  "Ext.device.tunnel.Abstract": [],
  "Ext.device.tunnel.Connection": [],
  "Ext.device.tunnel.Sencha": [],
  "Ext.device.tunnel.Simulator": [],
  "Ext.direct.Event": [
    "direct.event"
  ],
  "Ext.direct.ExceptionEvent": [
    "direct.exception"
  ],
  "Ext.direct.JsonProvider": [
    "direct.jsonprovider"
  ],
  "Ext.direct.Manager": [],
  "Ext.direct.PollingProvider": [
    "direct.pollingprovider"
  ],
  "Ext.direct.Provider": [
    "direct.provider"
  ],
  "Ext.direct.RemotingEvent": [
    "direct.rpc"
  ],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [
    "direct.remotingprovider"
  ],
  "Ext.direct.Transaction": [
    "direct.transaction"
  ],
  "Ext.dom.CompositeElement": [],
  "Ext.event.Controller": [],
  "Ext.event.Dispatcher": [],
  "Ext.event.Dom": [],
  "Ext.event.Event": [],
  "Ext.event.ListenerStack": [],
  "Ext.event.Touch": [],
  "Ext.event.publisher.ComponentDelegation": [],
  "Ext.event.publisher.ComponentPaint": [],
  "Ext.event.publisher.ComponentSize": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.event.publisher.TouchGesture": [],
  "Ext.event.recognizer.DoubleTap": [],
  "Ext.event.recognizer.Drag": [],
  "Ext.event.recognizer.EdgeSwipe": [],
  "Ext.event.recognizer.HorizontalSwipe": [],
  "Ext.event.recognizer.LongPress": [],
  "Ext.event.recognizer.MultiTouch": [],
  "Ext.event.recognizer.Pinch": [],
  "Ext.event.recognizer.Recognizer": [],
  "Ext.event.recognizer.Rotate": [],
  "Ext.event.recognizer.SingleTouch": [],
  "Ext.event.recognizer.Swipe": [],
  "Ext.event.recognizer.Tap": [],
  "Ext.event.recognizer.Touch": [],
  "Ext.event.recognizer.VerticalSwipe": [],
  "Ext.field.Checkbox": [
    "widget.checkboxfield"
  ],
  "Ext.field.DatePicker": [
    "widget.datepickerfield"
  ],
  "Ext.field.DatePickerNative": [
    "widget.datepickernativefield"
  ],
  "Ext.field.Email": [
    "widget.emailfield"
  ],
  "Ext.field.Field": [
    "widget.field"
  ],
  "Ext.field.File": [
    "widget.filefield"
  ],
  "Ext.field.FileInput": [
    "widget.fileinput"
  ],
  "Ext.field.Hidden": [
    "widget.hiddenfield"
  ],
  "Ext.field.Input": [
    "widget.input"
  ],
  "Ext.field.Number": [
    "widget.numberfield"
  ],
  "Ext.field.Password": [
    "widget.passwordfield"
  ],
  "Ext.field.Radio": [
    "widget.radiofield"
  ],
  "Ext.field.Search": [
    "widget.searchfield"
  ],
  "Ext.field.Select": [
    "widget.selectfield"
  ],
  "Ext.field.Slider": [
    "widget.sliderfield"
  ],
  "Ext.field.Spinner": [
    "widget.spinnerfield"
  ],
  "Ext.field.Text": [
    "widget.textfield"
  ],
  "Ext.field.TextArea": [
    "widget.textareafield"
  ],
  "Ext.field.TextAreaInput": [
    "widget.textareainput"
  ],
  "Ext.field.Toggle": [
    "widget.togglefield"
  ],
  "Ext.field.Url": [
    "widget.urlfield"
  ],
  "Ext.form.FieldSet": [
    "widget.fieldset"
  ],
  "Ext.form.Panel": [
    "widget.formpanel"
  ],
  "Ext.fx.Animation": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [
    "animation.cube"
  ],
  "Ext.fx.animation.Fade": [
    "animation.fade",
    "animation.fadeIn"
  ],
  "Ext.fx.animation.FadeOut": [
    "animation.fadeOut"
  ],
  "Ext.fx.animation.Flip": [
    "animation.flip"
  ],
  "Ext.fx.animation.Pop": [
    "animation.pop",
    "animation.popIn"
  ],
  "Ext.fx.animation.PopOut": [
    "animation.popOut"
  ],
  "Ext.fx.animation.Slide": [
    "animation.slide",
    "animation.slideIn"
  ],
  "Ext.fx.animation.SlideOut": [
    "animation.slideOut"
  ],
  "Ext.fx.animation.Wipe": [],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [
    "easing.ease-in"
  ],
  "Ext.fx.easing.EaseOut": [
    "easing.ease-out"
  ],
  "Ext.fx.easing.Linear": [
    "easing.linear"
  ],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [
    "fx.layout.card.cover"
  ],
  "Ext.fx.layout.card.Cube": [
    "fx.layout.card.cube"
  ],
  "Ext.fx.layout.card.Fade": [
    "fx.layout.card.fade"
  ],
  "Ext.fx.layout.card.Flip": [
    "fx.layout.card.flip"
  ],
  "Ext.fx.layout.card.Pop": [
    "fx.layout.card.pop"
  ],
  "Ext.fx.layout.card.Reveal": [
    "fx.layout.card.reveal"
  ],
  "Ext.fx.layout.card.Scroll": [
    "fx.layout.card.scroll"
  ],
  "Ext.fx.layout.card.ScrollCover": [
    "fx.layout.card.scrollcover"
  ],
  "Ext.fx.layout.card.ScrollReveal": [
    "fx.layout.card.scrollreveal"
  ],
  "Ext.fx.layout.card.Slide": [
    "fx.layout.card.slide"
  ],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [],
  "Ext.layout.Abstract": [],
  "Ext.layout.Box": [
    "layout.tablebox"
  ],
  "Ext.layout.Card": [
    "layout.card"
  ],
  "Ext.layout.Default": [
    "layout.auto",
    "layout.default"
  ],
  "Ext.layout.Fit": [
    "layout.fit"
  ],
  "Ext.layout.FlexBox": [
    "layout.box"
  ],
  "Ext.layout.Float": [
    "layout.float"
  ],
  "Ext.layout.HBox": [
    "layout.hbox"
  ],
  "Ext.layout.VBox": [
    "layout.vbox"
  ],
  "Ext.layout.wrapper.BoxDock": [],
  "Ext.layout.wrapper.Dock": [],
  "Ext.layout.wrapper.Inner": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.Filterable": [],
  "Ext.mixin.Mixin": [],
  "Ext.mixin.Observable": [],
  "Ext.mixin.Progressable": [],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Sortable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.navigation.Bar": [],
  "Ext.navigation.View": [
    "widget.navigationview"
  ],
  "Ext.picker.Date": [
    "widget.datepicker"
  ],
  "Ext.picker.Picker": [
    "widget.picker"
  ],
  "Ext.picker.Slot": [
    "widget.pickerslot"
  ],
  "Ext.plugin.BufferedList": [
    "plugin.bufferedlist"
  ],
  "Ext.plugin.ListPaging": [
    "plugin.listpaging"
  ],
  "Ext.plugin.PullRefresh": [
    "plugin.pullrefresh"
  ],
  "Ext.plugin.SortableList": [
    "plugin.sortablelist"
  ],
  "Ext.scroll.Indicator": [],
  "Ext.scroll.Scroller": [],
  "Ext.scroll.View": [],
  "Ext.scroll.indicator.Abstract": [],
  "Ext.scroll.indicator.CssTransform": [],
  "Ext.scroll.indicator.Rounded": [],
  "Ext.scroll.indicator.ScrollPosition": [],
  "Ext.slider.Slider": [
    "widget.slider"
  ],
  "Ext.slider.Thumb": [
    "widget.thumb"
  ],
  "Ext.slider.Toggle": [],
  "Ext.tab.Bar": [
    "widget.tabbar"
  ],
  "Ext.tab.Panel": [
    "widget.tabpanel"
  ],
  "Ext.tab.Tab": [
    "widget.tab"
  ],
  "Ext.table.Cell": [
    "widget.tablecell"
  ],
  "Ext.table.Row": [
    "widget.tablerow"
  ],
  "Ext.table.Table": [
    "widget.table"
  ],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Audio": [],
  "Ext.util.BufferedCollection": [],
  "Ext.util.Collection": [],
  "Ext.util.DelayedTask": [],
  "Ext.util.Draggable": [],
  "Ext.util.Droppable": [],
  "Ext.util.Filter": [],
  "Ext.util.Format": [],
  "Ext.util.Geolocation": [],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.Inflector": [],
  "Ext.util.InputBlocker": [],
  "Ext.util.LineSegment": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.PositionMap": [],
  "Ext.util.Region": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TapRepeater": [],
  "Ext.util.Translatable": [],
  "Ext.util.TranslatableGroup": [],
  "Ext.util.TranslatableList": [],
  "Ext.util.Wrapper": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.Default": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.ux.ActionOverFlowMenuButton": [],
  "Ext.ux.ApplicationMenu": [],
  "Ext.ux.ContextMenu": [],
  "Ext.ux.MenuButton": [],
  "Ext.ux.TabMenuButton": [],
  "Ext.ux.device.Analytics": [],
  "Ext.ux.device.Twitter": [],
  "Ext.ux.device.analytics.Abstract": [],
  "Ext.ux.device.analytics.Cordova": [],
  "Ext.ux.device.twitter.Abstract": [],
  "Ext.ux.device.twitter.Cordova": [],
  "Ext.ux.parse.Helper": [],
  "Ext.ux.parse.Model": [],
  "Ext.ux.parse.Proxy": [
    "proxy.parse"
  ],
  "Ext.ux.parse.Reader": [
    "reader.parse"
  ],
  "Ext.ux.parse.Store": [],
  "Ext.ux.parse.association.Pointer": [
    "association.pointer"
  ],
  "Ext.ux.parse.association.Relation": [
    "association.relation"
  ],
  "Ext.ux.slidenavigation.View": [
    "widget.slidenavigationview"
  ],
  "Ext.viewport.Android": [],
  "Ext.viewport.Default": [
    "widget.viewport"
  ],
  "Ext.viewport.Ios": [],
  "Ext.viewport.Viewport": [],
  "Ext.viewport.WindowsPhone": [],
  "Mat.controller.BlocoJo": [],
  "Mat.controller.Classes": [],
  "Mat.controller.EngineJogo": [],
  "Mat.controller.Fases": [],
  "Mat.controller.Jogo": [],
  "Mat.controller.MainJogo": [],
  "Mat.controller.Niveis": [],
  "Mat.controller.Ranking": [],
  "Mat.controller.Usuarios": [],
  "Mat.model.Classes": [],
  "Mat.model.Fases": [],
  "Mat.model.FasesLocal": [],
  "Mat.model.Jogo": [],
  "Mat.model.JogoLocal": [],
  "Mat.model.Niveis": [],
  "Mat.model.NiveisLocal": [],
  "Mat.model.Ranking": [],
  "Mat.model.Usuarios": [],
  "Mat.store.Classes": [],
  "Mat.store.Fases": [],
  "Mat.store.FasesLocal": [],
  "Mat.store.Jogo": [],
  "Mat.store.JogoLocal": [],
  "Mat.store.Niveis": [],
  "Mat.store.NiveisLocal": [],
  "Mat.store.Ranking": [],
  "Mat.store.Usuarios": [],
  "Mat.view.BlocoJogo": [
    "widget.BlocoJogo"
  ],
  "Mat.view.Classes.Classes": [
    "widget.Classes"
  ],
  "Mat.view.Classes.ContainerClasses": [
    "widget.ContainerClasses"
  ],
  "Mat.view.Classes.EditorClasses": [
    "widget.EditorClasses"
  ],
  "Mat.view.Classes.ListClasses": [
    "widget.ListClasses"
  ],
  "Mat.view.Classes.SearchBarClasses": [
    "widget.SearchBarClasses"
  ],
  "Mat.view.EngineJogo": [
    "widget.EngineJogo"
  ],
  "Mat.view.Fases.ContainerFases": [
    "widget.ContainerFases"
  ],
  "Mat.view.Fases.EditorFases": [
    "widget.EditorFases"
  ],
  "Mat.view.Fases.Fases": [
    "widget.Fases"
  ],
  "Mat.view.Fases.ListFases": [
    "widget.ListFases"
  ],
  "Mat.view.Fases.SearchBarFases": [
    "widget.SearchBarFases"
  ],
  "Mat.view.Jogo.ContainerJogo": [
    "widget.ContainerJogo"
  ],
  "Mat.view.Jogo.EditorJogo": [
    "widget.EditorJogo"
  ],
  "Mat.view.Jogo.Jogo": [
    "widget.Jogo"
  ],
  "Mat.view.Jogo.ListJogo": [
    "widget.ListJogo"
  ],
  "Mat.view.Jogo.SearchBarJogo": [
    "widget.SearchBarJogo"
  ],
  "Mat.view.Main": [
    "widget.Main"
  ],
  "Mat.view.MainJogo": [
    "widget.MainJogo"
  ],
  "Mat.view.MenuJogo": [
    "widget.MenuJogo"
  ],
  "Mat.view.Niveis.ContainerNiveis": [
    "widget.ContainerNiveis"
  ],
  "Mat.view.Niveis.EditorNiveis": [
    "widget.EditorNiveis"
  ],
  "Mat.view.Niveis.ListNiveis": [
    "widget.ListNiveis"
  ],
  "Mat.view.Niveis.Niveis": [
    "widget.Niveis"
  ],
  "Mat.view.Niveis.SearchBarNiveis": [
    "widget.SearchBarNiveis"
  ],
  "Mat.view.Ranking.ContainerRanking": [
    "widget.ContainerRanking"
  ],
  "Mat.view.Ranking.EditorRanking": [
    "widget.EditorRanking"
  ],
  "Mat.view.Ranking.ListRanking": [
    "widget.ListRanking"
  ],
  "Mat.view.Ranking.Ranking": [
    "widget.Ranking"
  ],
  "Mat.view.Ranking.SearchBarRanking": [
    "widget.SearchBarRanking"
  ],
  "Mat.view.SelecionaFases": [
    "widget.SelecionaFases"
  ],
  "Mat.view.SelecionaNiveis": [
    "widget.SelecionaNiveis"
  ],
  "Mat.view.Usuarios.ContainerUsuarios": [
    "widget.ContainerUsuarios"
  ],
  "Mat.view.Usuarios.EditorUsuarios": [
    "widget.EditorUsuarios"
  ],
  "Mat.view.Usuarios.ListUsuarios": [
    "widget.ListUsuarios"
  ],
  "Mat.view.Usuarios.SearchBarUsuarios": [
    "widget.SearchBarUsuarios"
  ],
  "Mat.view.Usuarios.Usuarios": [
    "widget.Usuarios"
  ]
});


/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is
 * provided to support globbing requires, custom xtypes, and other
 * metadata-driven class system features
 */


